db:
  image: postgres
  environment:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
memdb:
  image: redis
qubie:
  build: .
  links:
    - db
    - memdb
  ports:
    - "5102:5102"
  environment:
    - SECRET_TOKEN
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_REGION
